# Deploy completo a Firebase al hacer push a main
# https://github.com/firebase/firebase-tools

name: Deploy full Firebase project on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build

      - name: Deploy all Firebase services
        uses: w9jds/firebase-action@v13.26.0
        with:
          args: deploy --only hosting,functions,firestore:rules,storage:rules
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARGARG_LOGISTICA }}
          PROJECT_ID: cargarg-logistica
